FROM python:3.10.12

WORKDIR /app
COPY /requirements.train.txt .
RUN pip install --no-cache-dir -r requirements.train.txt

COPY pipeline/ pipeline/
COPY db/ db/
COPY dbtocsv.py dbtocsv.py

VOLUME ["/app/models"]
RUN mkdir -p /app/models

EXPOSE 6001
EXPOSE 7001

CMD ["python", "pipeline/training_pipeline.py"]