FROM python:3.10.12

WORKDIR /app
COPY /requirements.train.txt .
RUN pip install --no-cache-dir -r requirements.train.txt
# RUN jenkins-plugin-cli --plugins envinject

COPY pipeline_testing/ .

VOLUME ["/app/models"]
RUN mkdir -p /app/models

CMD ["python", "training_pipeline.py"]