FROM python:3.10-slim

WORKDIR /app

COPY requirements.kafka.txt .
RUN pip install --no-cache-dir -r requirements.kafka.txt

VOLUME ["/app/models"]

COPY kafka_import/ kafka_import/
COPY evaluation/ evaluation/
COPY db/ db/

CMD ["python", "evaluation/kafka_live.py"]
